---
groups:
- name: build-canary
  jobs:
  - build-canary-vm
  - ant
  - bee
  - dodo
  - elk
  - fox

resources:
- name: saturday-night-fever
  type: time
  icon: clock
  source:
    location: America/Los_Angeles
    start: 6:00 PM
    stop: 6:01 PM
    days: [Saturday]

- name: devenv
  type: git
  icon: github-box
  source:
    uri: git@github.com:cf-routing/devenv
    private_key: ((github_private_key.private_key))
    branch: develop

jobs:
- name: build-canary-vm
  plan:
    - in_parallel:
      - get: devenv
      - get: saturday-night-fever
        trigger: true
    - task: build-vm
      file: devenv/pipeline/tasks/build_canary_vm.yml
      params:
        GCP_SERVICE_ACCOUNT_KEY: ((shared_gcp_account_creds))
    - task: install-devenv
      file: devenv/pipeline/tasks/install_devenv.yml
      params:
        GCP_SERVICE_ACCOUNT_KEY: ((shared_gcp_account_creds))
    - task: capture-image
      file: devenv/pipeline/tasks/capture_image.yml
      params:
        GCP_SERVICE_ACCOUNT_KEY: ((shared_gcp_account_creds))

# WORKSTATIONS
- name: ant
  plan:
    - in_parallel:
      - get: devenv
        passed: [build-canary-vm]
        trigger: true
    - task: build-workstation
      file: devenv/pipeline/tasks/build_workstation.yml
      params:
        GCP_SERVICE_ACCOUNT_KEY: ((shared_gcp_account_creds))
        WORKSTATION_NAME: ant

- name: bee
  plan:
    - in_parallel:
      - get: devenv
        passed: [build-canary-vm]
        trigger: true
    - task: build-workstation
      file: devenv/pipeline/tasks/build_workstation.yml
      params:
        GCP_SERVICE_ACCOUNT_KEY: ((shared_gcp_account_creds))
        WORKSTATION_NAME: bee

- name: dodo
  plan:
    - in_parallel:
      - get: devenv
        passed: [build-canary-vm]
        trigger: true
    - task: build-workstation
      file: devenv/pipeline/tasks/build_workstation.yml
      params:
        GCP_SERVICE_ACCOUNT_KEY: ((shared_gcp_account_creds))
        WORKSTATION_NAME: dodo

- name: elk
  plan:
    - in_parallel:
      - get: devenv
        passed: [build-canary-vm]
        trigger: true
    - task: build-workstation
      file: devenv/pipeline/tasks/build_workstation.yml
      params:
        GCP_SERVICE_ACCOUNT_KEY: ((shared_gcp_account_creds))
        WORKSTATION_NAME: elk

- name: fox
  plan:
    - in_parallel:
      - get: devenv
        passed: [build-canary-vm]
        trigger: true
    - task: build-workstation
      file: devenv/pipeline/tasks/build_workstation.yml
      params:
        GCP_SERVICE_ACCOUNT_KEY: ((shared_gcp_account_creds))
        WORKSTATION_NAME: fox
