---
groups:
- name: build-canary
  jobs:
  - build-image
  - accept
  - ant
  - bee
  - canary
  - dodo
  - dog
  - elk
  - fox

resources:
- name: saturday-night-fever
  type: time
  icon: clock
  source:
    location: America/Los_Angeles
    start: 6:00 PM
    stop: 6:10 PM
    days: [Saturday]

- name: devenv
  type: git
  icon: github-box
  source:
    uri: git@github.com:cf-routing/devenv
    private_key: ((github_private_key.private_key))
    branch: develop

jobs:
- name: build-image
  max_in_flight: 1
  plan:
    - in_parallel:
      - get: devenv
        trigger: true
    - task: build-vm
      file: devenv/pipeline/tasks/build_image_vm.yml
      params:
        GCP_SERVICE_ACCOUNT_KEY: ((shared_gcp_account_creds))
        MACHINE_NAME: image-vm
    - task: install-devenv
      file: devenv/pipeline/tasks/install_devenv.yml
      params:
        GCP_SERVICE_ACCOUNT_KEY: ((shared_gcp_account_creds))
        MACHINE_NAME: image-vm
    - task: capture-image
      file: devenv/pipeline/tasks/capture_image.yml
      params:
        GCP_SERVICE_ACCOUNT_KEY: ((shared_gcp_account_creds))
        MACHINE_NAME: image-vm

# WORKSTATIONS
- name: accept
  plan:
    - in_parallel:
      - get: saturday-night-fever
        trigger: true
      - get: devenv
    - task: build-workstation
      file: devenv/pipeline/tasks/build_workstation.yml
      params:
        GCP_SERVICE_ACCOUNT_KEY: ((shared_gcp_account_creds))
        WORKSTATION_NAME: accept

- name: ant
  plan:
    - in_parallel:
      - get: saturday-night-fever
        trigger: true
      - get: devenv
    - task: build-workstation
      file: devenv/pipeline/tasks/build_workstation.yml
      params:
        GCP_SERVICE_ACCOUNT_KEY: ((shared_gcp_account_creds))
        WORKSTATION_NAME: ant

- name: bee
  plan:
    - in_parallel:
      - get: saturday-night-fever
        trigger: true
      - get: devenv
    - task: build-workstation
      file: devenv/pipeline/tasks/build_workstation.yml
      params:
        GCP_SERVICE_ACCOUNT_KEY: ((shared_gcp_account_creds))
        WORKSTATION_NAME: bee

- name: canary
  plan:
    - in_parallel:
      - get: saturday-night-fever
        trigger: true
      - get: devenv
    - task: build-workstation
      file: devenv/pipeline/tasks/build_workstation.yml
      params:
        GCP_SERVICE_ACCOUNT_KEY: ((shared_gcp_account_creds))
        WORKSTATION_NAME: canary

- name: dodo
  plan:
    - in_parallel:
      - get: saturday-night-fever
        trigger: true
      - get: devenv
    - task: build-workstation
      file: devenv/pipeline/tasks/build_workstation.yml
      params:
        GCP_SERVICE_ACCOUNT_KEY: ((shared_gcp_account_creds))
        WORKSTATION_NAME: dodo

- name: dog
  plan:
    - in_parallel:
      - get: saturday-night-fever
        trigger: true
      - get: devenv
    - task: build-workstation
      file: devenv/pipeline/tasks/build_workstation.yml
      params:
        GCP_SERVICE_ACCOUNT_KEY: ((shared_gcp_account_creds))
        WORKSTATION_NAME: dog

- name: elk
  plan:
    - in_parallel:
      - get: saturday-night-fever
        trigger: true
      - get: devenv
    - task: build-workstation
      file: devenv/pipeline/tasks/build_workstation.yml
      params:
        GCP_SERVICE_ACCOUNT_KEY: ((shared_gcp_account_creds))
        WORKSTATION_NAME: elk

- name: fox
  plan:
    - in_parallel:
      - get: saturday-night-fever
        trigger: true
      - get: devenv
    - task: build-workstation
      file: devenv/pipeline/tasks/build_workstation.yml
      params:
        GCP_SERVICE_ACCOUNT_KEY: ((shared_gcp_account_creds))
        WORKSTATION_NAME: fox
